#!/usr/bin/env python3
"""
SQLite to PostgreSQL Migration Script

Exports StdOut SQLite database to PostgreSQL-compatible SQL dump.
Phase 1.2: PostgreSQL Abstraction Layer migration utility.

Usage:
    # Export SQLite to SQL file
    python3 migrate-sqlite-to-postgres.py \\
        --sqlite-path ./data/stdout.db \\
        --export-sql ./migration.sql

    # Then import to PostgreSQL:
    docker exec -i stdout-postgres psql -U stdout -d stdout < migration.sql

Features:
    - Exports schema (CREATE TABLE statements)
    - Exports data (INSERT statements)
    - Converts SQLite types to PostgreSQL types
    - Handles TEXT vs VARCHAR differences
    - Preserves foreign keys and indexes
    - Includes transaction wrapping
"""

import argparse
import sqlite3
import sys
from pathlib import Path
from typing import List, Tuple


# Type mapping: SQLite → PostgreSQL
TYPE_MAP = {
    'INTEGER': 'INTEGER',
    'TEXT': 'TEXT',
    'REAL': 'REAL',
    'BLOB': 'BYTEA',
    # Drizzle-specific timestamp columns
    'INTEGER NOT NULL': 'INTEGER NOT NULL',
    'TEXT NOT NULL': 'TEXT NOT NULL',
}


def get_table_schema(cursor: sqlite3.Cursor, table_name: str) -> str:
    """Extract CREATE TABLE statement for a table."""
    cursor.execute(f"SELECT sql FROM sqlite_master WHERE type='table' AND name='{table_name}'")
    result = cursor.fetchone()
    if not result:
        raise ValueError(f"Table {table_name} not found")

    create_sql = result[0]

    # Convert SQLite syntax to PostgreSQL
    # SQLite uses AUTOINCREMENT, PostgreSQL uses SERIAL
    create_sql = create_sql.replace('AUTOINCREMENT', '')

    # SQLite's INTEGER PRIMARY KEY is auto-incrementing, PostgreSQL needs SERIAL
    # However, Drizzle uses TEXT for IDs (nanoid), so this won't apply to StdOut

    return create_sql


def get_table_data(cursor: sqlite3.Cursor, table_name: str) -> List[Tuple]:
    """Extract all rows from a table."""
    cursor.execute(f"SELECT * FROM {table_name}")
    return cursor.fetchall()


def get_column_names(cursor: sqlite3.Cursor, table_name: str) -> List[str]:
    """Get column names for a table."""
    cursor.execute(f"PRAGMA table_info({table_name})")
    return [row[1] for row in cursor.fetchall()]


def format_value(value) -> str:
    """Format a Python value for PostgreSQL SQL."""
    if value is None:
        return 'NULL'
    elif isinstance(value, str):
        # Escape single quotes for SQL
        escaped = value.replace("'", "''")
        return f"'{escaped}'"
    elif isinstance(value, (int, float)):
        return str(value)
    elif isinstance(value, bytes):
        # Convert bytes to PostgreSQL bytea format
        return f"'\\x{value.hex()}'"
    else:
        return f"'{str(value)}'"


def generate_insert_statement(table_name: str, columns: List[str], row: Tuple) -> str:
    """Generate INSERT statement for a row."""
    column_list = ', '.join(columns)
    value_list = ', '.join(format_value(v) for v in row)
    return f"INSERT INTO {table_name} ({column_list}) VALUES ({value_list});"


def export_database(sqlite_path: str, output_sql_path: str):
    """Export SQLite database to PostgreSQL SQL dump."""

    if not Path(sqlite_path).exists():
        print(f"❌ SQLite database not found: {sqlite_path}")
        sys.exit(1)

    print(f"📦 Exporting SQLite database: {sqlite_path}")
    print(f"📝 Output SQL file: {output_sql_path}")

    conn = sqlite3.connect(sqlite_path)
    cursor = conn.cursor()

    # Get all tables (exclude SQLite internal tables and Drizzle migrations)
    cursor.execute("""
        SELECT name FROM sqlite_master
        WHERE type='table'
        AND name NOT LIKE 'sqlite_%'
        ORDER BY name
    """)
    tables = [row[0] for row in cursor.fetchall()]

    print(f"\n📋 Found {len(tables)} tables to migrate:")
    for table in tables:
        cursor.execute(f"SELECT COUNT(*) FROM {table}")
        count = cursor.fetchone()[0]
        print(f"  - {table}: {count} rows")

    # Write SQL dump
    with open(output_sql_path, 'w') as f:
        # Header
        f.write("-- StdOut SQLite → PostgreSQL Migration\n")
        f.write("-- Generated by migrate-sqlite-to-postgres.py\n")
        f.write("-- Phase 1.2: PostgreSQL Abstraction Layer\n\n")

        # Start transaction
        f.write("BEGIN;\n\n")

        # Export schema (CREATE TABLE statements)
        f.write("-- ==============================================\n")
        f.write("-- SCHEMA CREATION\n")
        f.write("-- ==============================================\n\n")

        for table in tables:
            # Skip Drizzle migrations table (will be recreated by drizzle-kit)
            if table == '__drizzle_migrations':
                f.write(f"-- Skipping {table} (will be recreated by drizzle-kit migrate)\n\n")
                continue

            schema = get_table_schema(cursor, table)
            f.write(f"{schema};\n\n")

        # Export data (INSERT statements)
        f.write("-- ==============================================\n")
        f.write("-- DATA INSERTION\n")
        f.write("-- ==============================================\n\n")

        for table in tables:
            # Skip Drizzle migrations table
            if table == '__drizzle_migrations':
                continue

            columns = get_column_names(cursor, table)
            rows = get_table_data(cursor, table)

            f.write(f"-- Table: {table} ({len(rows)} rows)\n")

            if rows:
                for row in rows:
                    insert_stmt = generate_insert_statement(table, columns, row)
                    f.write(f"{insert_stmt}\n")
                f.write("\n")
            else:
                f.write("-- (empty table)\n\n")

        # Commit transaction
        f.write("COMMIT;\n\n")

        # Reset sequences (PostgreSQL-specific)
        f.write("-- ==============================================\n")
        f.write("-- RESET SEQUENCES (if any)\n")
        f.write("-- ==============================================\n\n")
        f.write("-- StdOut uses TEXT IDs (nanoid), no sequences to reset\n\n")

        # Footer
        f.write("-- Migration complete\n")
        f.write(f"-- Tables migrated: {len([t for t in tables if t != '__drizzle_migrations'])}\n")

    conn.close()

    print(f"\n✅ Migration SQL generated successfully!")
    print(f"📄 File: {output_sql_path}")
    print(f"\n📌 Next steps:")
    print(f"1. Start PostgreSQL:")
    print(f"   docker compose -f docker-compose.yml -f docker-compose.postgres.yml up -d postgres")
    print(f"\n2. Run migrations to create schema:")
    print(f"   DATABASE_TYPE=postgres DATABASE_URL='postgresql://...' npm run db:migrate")
    print(f"\n3. Import data:")
    print(f"   docker exec -i stdout-postgres psql -U stdout -d stdout < {output_sql_path}")
    print(f"\n4. Verify:")
    print(f"   docker exec stdout-postgres psql -U stdout -d stdout -c '\\dt'")
    print(f"\n5. Start StdOut in PostgreSQL mode:")
    print(f"   docker compose -f docker-compose.yml -f docker-compose.postgres.yml up -d")


def main():
    parser = argparse.ArgumentParser(
        description='Migrate StdOut SQLite database to PostgreSQL',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Export SQLite to SQL file
  python3 migrate-sqlite-to-postgres.py \\
      --sqlite-path ./data/stdout.db \\
      --export-sql ./migration.sql

  # Then import to PostgreSQL:
  docker exec -i stdout-postgres psql -U stdout -d stdout < migration.sql
"""
    )

    parser.add_argument(
        '--sqlite-path',
        required=True,
        help='Path to SQLite database file (e.g., ./data/stdout.db)'
    )

    parser.add_argument(
        '--export-sql',
        required=True,
        help='Path to output SQL file (e.g., ./migration.sql)'
    )

    args = parser.parse_args()

    export_database(args.sqlite_path, args.export_sql)


if __name__ == '__main__':
    main()
